[package]
name = "dual_sense_tester"
version = "0.1.0"
edition = "2024"

[dependencies]
hidapi = "2.2"
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
eframe = "0.26"